/**
 * Flyer HTML files with original per-layout styles (exported from git).
 * Generated by `node scripts/export-classic-flyers.mjs` — do not edit by hand.
 */
export const CLASSIC_FLYER_FILES = [
  "flyer-arcade.html",
  "flyer-bold.html",
  "flyer-families-home-portal.html",
  "flyer-feature-attendance.html",
  "flyer-feature-bulletin.html",
  "flyer-feature-engagement.html",
  "flyer-feature-hall-of-fame.html",
  "flyer-feature-houses.html",
  "flyer-feature-id-cards-themes.html",
  "flyer-feature-library.html",
  "flyer-feature-notifications.html",
  "flyer-feature-raffle.html",
  "flyer-feature-rewards-shop.html",
  "flyer-feature-student-kiosk.html",
  "flyer-feature-student-portal.html",
  "flyer-minimal.html",
  "flyer-parents.html",
  "flyer-principal-culture.html",
  "flyer-principal-data.html",
  "flyer-principal-roi.html",
  "flyer-principal-rollout.html",
  "flyer-principal-tech.html",
  "flyer-professional.html",
  "flyer-retro.html",
  "flyer-scholastic.html",
  "flyer-staff-pbis-playbook.html",
  "flyer-students-elementary-2.html",
  "flyer-students-elementary.html",
  "flyer-students-high-2.html",
  "flyer-students-high.html",
  "flyer-students-middle-2.html",
  "flyer-students-middle.html",
  "flyer-sunset.html",
  "flyer-teachers-quickstart.html",
  "flyer-private-school-pillar-proposal.html",
  "flyer-private-school-funding.html"
] as const;

export type ClassicFlyerFile = (typeof CLASSIC_FLYER_FILES)[number];

export function hasClassicFlyer(href: string): boolean {
  const name = href.replace(/^\/marketing\//, '').replace(/^\/marketing\/classic\//, '');
  return (CLASSIC_FLYER_FILES as readonly string[]).includes(name);
}

export function classicFlyerHref(href: string): string {
  const name = href.replace(/^\/marketing\//, '').replace(/^\/marketing\/classic\//, '');
  return `/marketing/classic/${name}`;
}
