import type { House } from '@/lib/types';

/** RCA House System preset pack (names, values, colors — no trademarked assets). */
export const RCA_HOUSE_PRESET_PACK: Omit<House, 'id' | 'points' | 'lifetimePoints'>[] = [
  {
    name: 'Amistad',
    value: 'Friendship',
    color: '#E11D48',
    emoji: '🤝',
    motto: 'Friends lift each other up.',
    rcaPresetKey: 'amistad',
    sortOrder: 0,
  },
  {
    name: 'Altruismo',
    value: 'Giving',
    color: '#059669',
    emoji: '🌿',
    motto: 'We give more than we take.',
    rcaPresetKey: 'altruismo',
    sortOrder: 1,
  },
  {
    name: 'Isibindi',
    value: 'Courage',
    color: '#D97706',
    emoji: '🛡️',
    motto: 'Brave hearts lead the way.',
    rcaPresetKey: 'isibindi',
    sortOrder: 2,
  },
  {
    name: 'Rêveur',
    value: 'Dreams',
    color: '#7C3AED',
    emoji: '✨',
    motto: 'Dream big, act bold.',
    rcaPresetKey: 'reveur',
    sortOrder: 3,
  },
  {
    name: 'Nukumori',
    value: 'Kindness',
    color: '#EC4899',
    emoji: '💗',
    motto: 'Kindness is our superpower.',
    rcaPresetKey: 'nukumori',
    sortOrder: 4,
  },
  {
    name: 'Onraka',
    value: 'Success',
    color: '#2563EB',
    emoji: '⭐',
    motto: 'Success is built together.',
    rcaPresetKey: 'onraka',
    sortOrder: 5,
  },
  {
    name: 'Protos',
    value: 'Unity',
    color: '#0D9488',
    emoji: '🔗',
    motto: 'Stronger as one.',
    rcaPresetKey: 'protos',
    sortOrder: 6,
  },
  {
    name: 'Sollevare',
    value: 'Uplift',
    color: '#CA8A04',
    emoji: '🌅',
    motto: 'We rise by lifting others.',
    rcaPresetKey: 'sollevare',
    sortOrder: 7,
  },
];
