import type { FeatureShowcasePromoProps } from "./featurePromoSchema";
import type { FeaturePromoVariantId } from "./featurePromoScripts";

/** Auto-generated — npm run generate:voiceover:feature */
export const defaultFeaturePromoPropsByVariant: Record<
  FeaturePromoVariantId,
  FeatureShowcasePromoProps
> = {
  epic: {
    variantId: "epic",
    timing: {
      introEnd: 259,
      segmentEnds: [464, 649, 922, 1105, 1288, 1470, 1656, 1880, 2073, 2268, 2414, 2568, 2720, 2874],
      total: 3182,
    },
    narration: [
      {
        id: "intro",
        label: "Intro",
        text: "This is a feature tour of LevelUp — every major tool schools use for rewards, recognition, and motivation.",
        file: "voiceover/feature/epic/intro.mp3",
        startFrame: 14,
        durationFrames: 235,
      },
      {
        id: "kiosk",
        label: "Kiosk",
        text: "Students step up to the kiosk, scan in, and see their world of points instantly.",
        file: "voiceover/feature/epic/kiosk.mp3",
        startFrame: 261,
        durationFrames: 191,
      },
      {
        id: "idCards",
        label: "ID cards",
        text: "Every student gets a digital ID card you can preview, print, and scan at the kiosk.",
        file: "voiceover/feature/epic/idCards.mp3",
        startFrame: 464,
        durationFrames: 173,
      },
      {
        id: "themes",
        label: "Themes",
        text: "Create a student card theme — type a prompt, choose colors and gradients, and watch the ID card preview update live.",
        file: "voiceover/feature/epic/themes.mp3",
        startFrame: 649,
        durationFrames: 261,
      },
      {
        id: "prizes",
        label: "Prizes",
        text: "The prize shop turns effort into something they can hold in their hands.",
        file: "voiceover/feature/epic/prizes.mp3",
        startFrame: 922,
        durationFrames: 171,
      },
      {
        id: "coupons",
        label: "Coupons",
        text: "Teachers print reward coupons without breaking stride in the classroom.",
        file: "voiceover/feature/epic/coupons.mp3",
        startFrame: 1105,
        durationFrames: 171,
      },
      {
        id: "raffle",
        label: "Raffle",
        text: "Weekly raffles transform everyday points into electric, school-wide moments.",
        file: "voiceover/feature/epic/raffle.mp3",
        startFrame: 1288,
        durationFrames: 170,
      },
      {
        id: "houses",
        label: "Houses",
        text: "House competitions unite grades in friendly rivalry that lasts all year.",
        file: "voiceover/feature/epic/houses.mp3",
        startFrame: 1470,
        durationFrames: 174,
      },
      {
        id: "hallOfFame",
        label: "Hall of Fame",
        text: "The Hall of Fame celebrates leaders on a display the whole school can see.",
        file: "voiceover/feature/epic/hallOfFame.mp3",
        startFrame: 1656,
        durationFrames: 212,
      },
      {
        id: "notifications",
        label: "Notifications",
        text: "Smart notifications keep staff ahead of inventory, milestones, and surprises.",
        file: "voiceover/feature/epic/notifications.mp3",
        startFrame: 1880,
        durationFrames: 181,
      },
      {
        id: "bulletin",
        label: "Bulletin",
        text: "The bulletin board broadcasts pride, news, and momentum.",
        file: "voiceover/feature/epic/bulletin.mp3",
        startFrame: 2073,
        durationFrames: 183,
      },
      {
        id: "library",
        label: "Library",
        text: "Library checkout weaves reading into the same rewards story.",
        file: "voiceover/feature/epic/library.mp3",
        startFrame: 2268,
        durationFrames: 134,
      },
      {
        id: "badges",
        label: "Badges",
        text: "Badges and goals give every student a path to be recognized.",
        file: "voiceover/feature/epic/badges.mp3",
        startFrame: 2414,
        durationFrames: 142,
      },
      {
        id: "analytics",
        label: "Analytics",
        text: "Insights reveal what is working — class by class, week by week.",
        file: "voiceover/feature/epic/analytics.mp3",
        startFrame: 2568,
        durationFrames: 140,
      },
      {
        id: "attendance",
        label: "Attendance",
        text: "Attendance ties the kiosk to how your school already runs the day.",
        file: "voiceover/feature/epic/attendance.mp3",
        startFrame: 2720,
        durationFrames: 142,
      },
      {
        id: "outro",
        label: "Outro",
        text: "LevelUp — one platform, countless ways to motivate. Welcome to what school rewards can be.",
        file: "voiceover/feature/epic/outro.mp3",
        startFrame: 2874,
        durationFrames: 218,
      }
    ],
    copy: {
      "introEyebrow": "Feature showcase",
      "introTagline": "Every major feature in one platform",
      "montageTitle": "Features that power your school",
      "montageSubtitle": "Kiosk · Rewards · Admin tools · Displays",
      "outroHeadline": "Built for real schools",
      "outroSubline": "Scan-first · Live sync · Built for students"
    },
    ttsVoice: "marin",
    musicVolume: 0.24,
    musicDuckRatio: 0.28,
    musicStyle: "cinematic",
    musicSrc: "background-music.mp3",
  },
  warm: {
    variantId: "warm",
    timing: {
      introEnd: 260,
      segmentEnds: [468, 664, 923, 1088, 1262, 1468, 1635, 1828, 2046, 2205, 2354, 2571, 2743, 2915],
      total: 3309,
    },
    narration: [
      {
        id: "intro",
        label: "Intro",
        text: "Hi — this is a feature tour of LevelUp: the tools for points, prizes, ID cards, raffles, and more.",
        file: "voiceover/feature/warm/intro.mp3",
        startFrame: 14,
        durationFrames: 236,
      },
      {
        id: "kiosk",
        label: "Kiosk",
        text: "Kids sign in at the kiosk in seconds, usually with a quick scan.",
        file: "voiceover/feature/warm/kiosk.mp3",
        startFrame: 262,
        durationFrames: 194,
      },
      {
        id: "idCards",
        label: "ID cards",
        text: "You can preview and print student ID cards right from the admin portal.",
        file: "voiceover/feature/warm/idCards.mp3",
        startFrame: 468,
        durationFrames: 184,
      },
      {
        id: "themes",
        label: "Themes",
        text: "Design themes in minutes — describe the look, adjust colors, and preview it on student ID cards.",
        file: "voiceover/feature/warm/themes.mp3",
        startFrame: 664,
        durationFrames: 247,
      },
      {
        id: "prizes",
        label: "Prizes",
        text: "They pick prizes they actually care about from the shop.",
        file: "voiceover/feature/warm/prizes.mp3",
        startFrame: 923,
        durationFrames: 153,
      },
      {
        id: "coupons",
        label: "Coupons",
        text: "Teachers print coupons when you want to reward on the spot.",
        file: "voiceover/feature/warm/coupons.mp3",
        startFrame: 1088,
        durationFrames: 162,
      },
      {
        id: "raffle",
        label: "Raffle",
        text: "Raffles are a fun Friday ritual — tickets from points they already earned.",
        file: "voiceover/feature/warm/raffle.mp3",
        startFrame: 1262,
        durationFrames: 194,
      },
      {
        id: "houses",
        label: "Houses",
        text: "Houses help homerooms and teams cheer for each other.",
        file: "voiceover/feature/warm/houses.mp3",
        startFrame: 1468,
        durationFrames: 155,
      },
      {
        id: "hallOfFame",
        label: "Hall of Fame",
        text: "Hall of Fame boards make shout-outs visible in the cafeteria or gym.",
        file: "voiceover/feature/warm/hallOfFame.mp3",
        startFrame: 1635,
        durationFrames: 181,
      },
      {
        id: "notifications",
        label: "Notifications",
        text: "Notifications mean fewer surprises about low stock or big milestones.",
        file: "voiceover/feature/warm/notifications.mp3",
        startFrame: 1828,
        durationFrames: 206,
      },
      {
        id: "bulletin",
        label: "Bulletin",
        text: "Bulletin boards keep families and students in the loop.",
        file: "voiceover/feature/warm/bulletin.mp3",
        startFrame: 2046,
        durationFrames: 147,
      },
      {
        id: "library",
        label: "Library",
        text: "Library tools track checkouts right beside rewards.",
        file: "voiceover/feature/warm/library.mp3",
        startFrame: 2205,
        durationFrames: 137,
      },
      {
        id: "badges",
        label: "Badges",
        text: "Badges and goals give quiet students a way to shine.",
        file: "voiceover/feature/warm/badges.mp3",
        startFrame: 2354,
        durationFrames: 205,
      },
      {
        id: "analytics",
        label: "Analytics",
        text: "Reports help you see who is engaging and where to help.",
        file: "voiceover/feature/warm/analytics.mp3",
        startFrame: 2571,
        durationFrames: 160,
      },
      {
        id: "attendance",
        label: "Attendance",
        text: "Attendance options connect sign-in to how you already take roll.",
        file: "voiceover/feature/warm/attendance.mp3",
        startFrame: 2743,
        durationFrames: 160,
      },
      {
        id: "outro",
        label: "Outro",
        text: "That is LevelUp — kind to kids, clear for teachers, and calm for the front office. We would love to show your school.",
        file: "voiceover/feature/warm/outro.mp3",
        startFrame: 2915,
        durationFrames: 304,
      }
    ],
    copy: {
      "introEyebrow": "Feature showcase",
      "introTagline": "See what LevelUp includes",
      "montageTitle": "Features your school will use",
      "montageSubtitle": "Student · Teacher · Admin",
      "outroHeadline": "Ready for your school?",
      "outroSubline": "Demo schools available · Scan-first kiosk"
    },
    ttsVoice: "coral",
    musicVolume: 0.22,
    musicDuckRatio: 0.28,
    musicStyle: "calm",
    musicSrc: "background-music.mp3",
  },
  pro: {
    variantId: "pro",
    timing: {
      introEnd: 332,
      segmentEnds: [540, 788, 1023, 1214, 1388, 1586, 1766, 1961, 2170, 2350, 2556, 2721, 2898, 3089],
      total: 3497,
    },
    narration: [
      {
        id: "intro",
        label: "Intro",
        text: "This walkthrough covers each LevelUp feature — kiosk, ID cards, themes, prizes, raffles, and admin modules.",
        file: "voiceover/feature/pro/intro.mp3",
        startFrame: 14,
        durationFrames: 308,
      },
      {
        id: "kiosk",
        label: "Kiosk",
        text: "Kiosk sign-in supports card, type, and scan workflows.",
        file: "voiceover/feature/pro/kiosk.mp3",
        startFrame: 334,
        durationFrames: 194,
      },
      {
        id: "idCards",
        label: "ID cards",
        text: "Student ID cards with admin preview, print layouts, and scan-ready barcodes.",
        file: "voiceover/feature/pro/idCards.mp3",
        startFrame: 540,
        durationFrames: 236,
      },
      {
        id: "themes",
        label: "Themes",
        text: "The theme designer builds card styles from a prompt and color palette with a live preview.",
        file: "voiceover/feature/pro/themes.mp3",
        startFrame: 788,
        durationFrames: 223,
      },
      {
        id: "prizes",
        label: "Prizes",
        text: "Configurable prize catalog with inventory awareness.",
        file: "voiceover/feature/pro/prizes.mp3",
        startFrame: 1023,
        durationFrames: 179,
      },
      {
        id: "coupons",
        label: "Coupons",
        text: "Teachers issue printable coupons tied to point rules.",
        file: "voiceover/feature/pro/coupons.mp3",
        startFrame: 1214,
        durationFrames: 162,
      },
      {
        id: "raffle",
        label: "Raffle",
        text: "Scheduled raffles with ticket rules and winner workflows.",
        file: "voiceover/feature/pro/raffle.mp3",
        startFrame: 1388,
        durationFrames: 186,
      },
      {
        id: "houses",
        label: "Houses",
        text: "House sorting, team totals, and display options.",
        file: "voiceover/feature/pro/houses.mp3",
        startFrame: 1586,
        durationFrames: 168,
      },
      {
        id: "hallOfFame",
        label: "Hall of Fame",
        text: "Public leaderboard displays for lifetime and period rankings.",
        file: "voiceover/feature/pro/hallOfFame.mp3",
        startFrame: 1766,
        durationFrames: 183,
      },
      {
        id: "notifications",
        label: "Notifications",
        text: "Notification policies for staff, inventory, and milestones.",
        file: "voiceover/feature/pro/notifications.mp3",
        startFrame: 1961,
        durationFrames: 197,
      },
      {
        id: "bulletin",
        label: "Bulletin",
        text: "Digital bulletin surfaces for announcements and media.",
        file: "voiceover/feature/pro/bulletin.mp3",
        startFrame: 2170,
        durationFrames: 168,
      },
      {
        id: "library",
        label: "Library",
        text: "Library module for loans, fees, and return incentives.",
        file: "voiceover/feature/pro/library.mp3",
        startFrame: 2350,
        durationFrames: 194,
      },
      {
        id: "badges",
        label: "Badges",
        text: "Achievement badges, goals, and category thresholds.",
        file: "voiceover/feature/pro/badges.mp3",
        startFrame: 2556,
        durationFrames: 153,
      },
      {
        id: "analytics",
        label: "Analytics",
        text: "Administrative insights across students and classes.",
        file: "voiceover/feature/pro/analytics.mp3",
        startFrame: 2721,
        durationFrames: 165,
      },
      {
        id: "attendance",
        label: "Attendance",
        text: "Attendance capture integrated with kiosk sign-in.",
        file: "voiceover/feature/pro/attendance.mp3",
        startFrame: 2898,
        durationFrames: 179,
      },
      {
        id: "outro",
        label: "Outro",
        text: "LevelUp reduces tool sprawl while keeping students on scan-first hardware. Request a walkthrough for your district.",
        file: "voiceover/feature/pro/outro.mp3",
        startFrame: 3089,
        durationFrames: 318,
      }
    ],
    copy: {
      "introEyebrow": "Feature overview",
      "introTagline": "Module-by-module walkthrough",
      "montageTitle": "Platform features",
      "montageSubtitle": "14 features · One system",
      "outroHeadline": "Deploy with confidence",
      "outroSubline": "Role-based access · Audit-friendly"
    },
    ttsVoice: "sage",
    musicVolume: 0.22,
    musicDuckRatio: 0.28,
    musicStyle: "default",
    musicSrc: "background-music.mp3",
  },
  hype: {
    variantId: "hype",
    timing: {
      introEnd: 362,
      segmentEnds: [542, 720, 976, 1150, 1296, 1437, 1588, 1732, 1883, 2027, 2191, 2332, 2472, 2607],
      total: 3010,
    },
    narration: [
      {
        id: "intro",
        label: "Intro",
        text: "Feature tour time — every LevelUp module, fast — kiosk, cards, themes, prizes, raffles, admin tools.",
        file: "voiceover/feature/hype/intro.mp3",
        startFrame: 14,
        durationFrames: 338,
      },
      {
        id: "kiosk",
        label: "Kiosk",
        text: "Kiosk check-in — boom — balance on screen.",
        file: "voiceover/feature/hype/kiosk.mp3",
        startFrame: 364,
        durationFrames: 166,
      },
      {
        id: "idCards",
        label: "ID cards",
        text: "ID cards — preview, print, scan — done.",
        file: "voiceover/feature/hype/idCards.mp3",
        startFrame: 542,
        durationFrames: 166,
      },
      {
        id: "themes",
        label: "Themes",
        text: "Build a theme — prompt, gradient, colors — card preview updates as you go.",
        file: "voiceover/feature/hype/themes.mp3",
        startFrame: 720,
        durationFrames: 244,
      },
      {
        id: "prizes",
        label: "Prizes",
        text: "Prize shop — scroll, tap, redeem.",
        file: "voiceover/feature/hype/prizes.mp3",
        startFrame: 976,
        durationFrames: 162,
      },
      {
        id: "coupons",
        label: "Coupons",
        text: "Teachers — print coupons — done.",
        file: "voiceover/feature/hype/coupons.mp3",
        startFrame: 1150,
        durationFrames: 134,
      },
      {
        id: "raffle",
        label: "Raffle",
        text: "Raffle week — tickets flying — winners loud.",
        file: "voiceover/feature/hype/raffle.mp3",
        startFrame: 1296,
        durationFrames: 129,
      },
      {
        id: "houses",
        label: "Houses",
        text: "Houses — team colors — scoreboards lit.",
        file: "voiceover/feature/hype/houses.mp3",
        startFrame: 1437,
        durationFrames: 139,
      },
      {
        id: "hallOfFame",
        label: "Hall of Fame",
        text: "Hall of Fame — legends on the wall.",
        file: "voiceover/feature/hype/hallOfFame.mp3",
        startFrame: 1588,
        durationFrames: 132,
      },
      {
        id: "notifications",
        label: "Notifications",
        text: "Notifications — ping — staff stays ahead.",
        file: "voiceover/feature/hype/notifications.mp3",
        startFrame: 1732,
        durationFrames: 139,
      },
      {
        id: "bulletin",
        label: "Bulletin",
        text: "Bulletin — headlines — hype in the hallway.",
        file: "voiceover/feature/hype/bulletin.mp3",
        startFrame: 1883,
        durationFrames: 132,
      },
      {
        id: "library",
        label: "Library",
        text: "Library — check out — earn while you read.",
        file: "voiceover/feature/hype/library.mp3",
        startFrame: 2027,
        durationFrames: 152,
      },
      {
        id: "badges",
        label: "Badges",
        text: "Badges — unlock — flex the streak.",
        file: "voiceover/feature/hype/badges.mp3",
        startFrame: 2191,
        durationFrames: 129,
      },
      {
        id: "analytics",
        label: "Analytics",
        text: "Insights — charts — know what hits.",
        file: "voiceover/feature/hype/analytics.mp3",
        startFrame: 2332,
        durationFrames: 128,
      },
      {
        id: "attendance",
        label: "Attendance",
        text: "Attendance — sign in — counted.",
        file: "voiceover/feature/hype/attendance.mp3",
        startFrame: 2472,
        durationFrames: 123,
      },
      {
        id: "outro",
        label: "Outro",
        text: "Stack it all with LevelUp — scan-first, synced live, built for schools that want energy. Let us run.",
        file: "voiceover/feature/hype/outro.mp3",
        startFrame: 2607,
        durationFrames: 313,
      }
    ],
    copy: {
      "introEyebrow": "FEATURE TOUR",
      "introTagline": "Everything LevelUp does",
      "montageTitle": "Feature stack",
      "montageSubtitle": "Real screens · Real tools",
      "outroHeadline": "Go all in",
      "outroSubline": "Kiosk · Raffle · HoF · More"
    },
    ttsVoice: "ash",
    musicVolume: 0.26,
    musicDuckRatio: 0.28,
    musicStyle: "upbeat",
    musicSrc: "background-music.mp3",
  },
  story: {
    variantId: "story",
    timing: {
      introEnd: 226,
      segmentEnds: [380, 573, 838, 1003, 1141, 1295, 1454, 1621, 1788, 1931, 2077, 2244, 2401, 2542],
      total: 2864,
    },
    narration: [
      {
        id: "intro",
        label: "Intro",
        text: "Walk through the features with us — from the morning kiosk to the admin tools that run the building.",
        file: "voiceover/feature/story/intro.mp3",
        startFrame: 14,
        durationFrames: 202,
      },
      {
        id: "kiosk",
        label: "Kiosk",
        text: "By first period, students are scanning in at the kiosk.",
        file: "voiceover/feature/story/kiosk.mp3",
        startFrame: 228,
        durationFrames: 140,
      },
      {
        id: "idCards",
        label: "ID cards",
        text: "The office already printed ID cards — students tap the same badge every day.",
        file: "voiceover/feature/story/idCards.mp3",
        startFrame: 380,
        durationFrames: 181,
      },
      {
        id: "themes",
        label: "Themes",
        text: "An admin creates the card theme once — colors and gradients — and every student ID matches.",
        file: "voiceover/feature/story/themes.mp3",
        startFrame: 573,
        durationFrames: 253,
      },
      {
        id: "prizes",
        label: "Prizes",
        text: "At lunch, someone cashes points for a prize they picked last week.",
        file: "voiceover/feature/story/prizes.mp3",
        startFrame: 838,
        durationFrames: 153,
      },
      {
        id: "coupons",
        label: "Coupons",
        text: "A teacher prints a coupon for kindness caught in the hallway.",
        file: "voiceover/feature/story/coupons.mp3",
        startFrame: 1003,
        durationFrames: 126,
      },
      {
        id: "raffle",
        label: "Raffle",
        text: "Friday assembly — raffle drums roll — tickets from all week.",
        file: "voiceover/feature/story/raffle.mp3",
        startFrame: 1141,
        durationFrames: 142,
      },
      {
        id: "houses",
        label: "Houses",
        text: "House points tick up after the pep rally challenge.",
        file: "voiceover/feature/story/houses.mp3",
        startFrame: 1295,
        durationFrames: 147,
      },
      {
        id: "hallOfFame",
        label: "Hall of Fame",
        text: "The Hall of Fame slide rotates new names at dismissal.",
        file: "voiceover/feature/story/hallOfFame.mp3",
        startFrame: 1454,
        durationFrames: 155,
      },
      {
        id: "notifications",
        label: "Notifications",
        text: "Meanwhile, notifications flag a low prize shelf before Monday.",
        file: "voiceover/feature/story/notifications.mp3",
        startFrame: 1621,
        durationFrames: 155,
      },
      {
        id: "bulletin",
        label: "Bulletin",
        text: "The bulletin board tells tomorrow’s spirit theme.",
        file: "voiceover/feature/story/bulletin.mp3",
        startFrame: 1788,
        durationFrames: 131,
      },
      {
        id: "library",
        label: "Library",
        text: "Library returns earn a quiet bonus point before bus call.",
        file: "voiceover/feature/story/library.mp3",
        startFrame: 1931,
        durationFrames: 134,
      },
      {
        id: "badges",
        label: "Badges",
        text: "A badge unlocks for the reader who finished the series.",
        file: "voiceover/feature/story/badges.mp3",
        startFrame: 2077,
        durationFrames: 155,
      },
      {
        id: "analytics",
        label: "Analytics",
        text: "After buses leave, admin scans insights before heading home.",
        file: "voiceover/feature/story/analytics.mp3",
        startFrame: 2244,
        durationFrames: 145,
      },
      {
        id: "attendance",
        label: "Attendance",
        text: "Attendance records from the kiosk are already in sync.",
        file: "voiceover/feature/story/attendance.mp3",
        startFrame: 2401,
        durationFrames: 129,
      },
      {
        id: "outro",
        label: "Outro",
        text: "One day, one thread — LevelUp ties the moments together so motivation does not reset at 3 p.m.",
        file: "voiceover/feature/story/outro.mp3",
        startFrame: 2542,
        durationFrames: 232,
      }
    ],
    copy: {
      "introEyebrow": "Feature walkthrough",
      "introTagline": "How the pieces connect",
      "montageTitle": "Features in action",
      "montageSubtitle": "Students first · Then the rest",
      "outroHeadline": "Same system, whole day",
      "outroSubline": "Motivation that lasts past homeroom"
    },
    ttsVoice: "marin",
    musicVolume: 0.23,
    musicDuckRatio: 0.28,
    musicStyle: "calm",
    musicSrc: "background-music.mp3",
  }
};

export function getDefaultFeaturePromoProps(
  variantId: FeaturePromoVariantId,
): FeatureShowcasePromoProps {
  return defaultFeaturePromoPropsByVariant[variantId];
}
