import type { IntroStep } from './types';
import { STAFF_AI_HELP_TOUR_TARGET, WIZARD_HELP_BUTTON_CLOSING } from '@/lib/wizardHelpCopy';

export const featuresTourSteps: IntroStep[] = [
  {
    id: 'features-intro',
    title: 'Advanced Features Tour',
    body: "Let's check out the coolest extra tools you can turn on anytime to make school even more fun!",
    onRoute: '/portal',
    extraRoutes: ['/admin'],
  },
  {
    id: 'features-houses',
    title: 'School Houses & Teams',
    body: 'Build school spirit by sorting students into Houses or Teams. Friendly competitions update live point totals all year long!',
    onRoute: '/portal',
    extraRoutes: ['/admin'],
    target: 'addon-link-houses',
    requireTarget: false,
  },
  {
    id: 'features-goals',
    title: 'Savings Goals & Wishlists',
    body: 'Help students practice saving! Kids can choose a big reward they want to work toward and watch their progress bar grow.',
    onRoute: '/portal',
    extraRoutes: ['/admin'],
    target: 'addon-link-goals',
    requireTarget: false,
  },
  {
    id: 'features-library',
    title: 'School Library & Book Lending',
    body: 'Turn the portal into a library desk. Scan barcodes on books to check them out to students, track return dates, and log reading levels.',
    onRoute: '/portal',
    extraRoutes: ['/admin'],
    target: 'portal-library',
    requireTarget: false,
  },
  {
    id: 'features-displays',
    title: 'Hallway TVs & Big Screens',
    body: 'Show live leaderboards and celebration banners on hallway screens or cafeteria TVs. Just open the display link on the TV browser!',
    onRoute: '/portal',
    extraRoutes: ['/admin'],
    target: 'addon-link-displays',
    requireTarget: false,
  },
  {
    id: 'features-student-portal',
    title: 'Home Access for Families',
    body: 'Let students log in from a home computer or tablet with their families to see their point balance, earned badges, and goals.',
    onRoute: '/portal',
    extraRoutes: ['/admin'],
    target: 'portal-student-home',
    requireTarget: false,
  },
  {
    id: 'features-classroom',
    title: 'Classroom Seating & Quick Praise',
    body: 'Teachers can lay out desks in rows or clusters, take attendance with one tap, and celebrate whole tables with festive sounds.',
    onRoute: '/portal',
    extraRoutes: ['/admin', '/teacher'],
    target: 'portal-print',
    requireTarget: false,
  },
  {
    id: 'features-badges',
    title: 'Custom Student Badges & Cards',
    body: 'Print student ID badges with student photos, custom school colors, barcodes, or tap-to-pay icons on standard paper or cardstock.',
    onRoute: '/portal',
    extraRoutes: ['/admin'],
    target: 'portal-redeem',
    requireTarget: false,
  },
  {
    id: 'features-finish',
    title: "You're Ready to Roll!",
    body: `You can turn on any of these tools whenever you need them. ${WIZARD_HELP_BUTTON_CLOSING}`,
    onRoute: '/portal',
    extraRoutes: ['/admin', '/teacher', '/student', '/hall-of-fame', '/student-home'],
    target: STAFF_AI_HELP_TOUR_TARGET,
  },
];
