import { STAFF_AI_HELP_TOUR_TARGET } from '@/lib/wizardHelpCopy';
import type { IntroStep } from './types';

export const teacherTourSteps: IntroStep[] = [
  {
    id: 'teacher-sign-in',
    title: 'Sign In First',
    body: 'Your school may not have teachers set up yet. Tap Sign in as admin and enter your admin passcode to explore the Teacher Portal.',
    onRoute: '/teacher',
    advanceOnTarget: 'staff-tab-coupons',
    navigateHint: 'Tap Sign in as admin and enter your admin passcode to continue.',
  },
  {
    id: 'teacher-points-tab',
    title: 'Give Points',
    body: 'This is your Points hub — print scannable coupons or use Manually Add for quick digital awards.',
    onRoute: '/teacher',
    target: 'staff-tab-coupons',
    requireTarget: true,
  },
  {
    id: 'teacher-print-section',
    title: 'Print Coupons',
    body: 'The Print coupons section is selected here. Pick a category and value, then generate a sheet of unique codes.',
    onRoute: '/teacher',
    target: 'section-tab-print',
    requireTarget: true,
    selectTab: 'coupons',
    selectSection: 'print',
  },
  {
    id: 'teacher-print',
    title: 'Print Settings',
    body: 'Adjust layout and quantity here, then generate your printable PDF of coupon codes.',
    onRoute: '/teacher',
    target: 'coupon-print-panel',
    requireTarget: true,
    selectTab: 'coupons',
    selectSection: 'print',
  },
  {
    id: 'teacher-generate',
    title: 'Generate!',
    body: 'This gives you a printable PDF of codes. Students scan these at the kiosk to bank their points.',
    onRoute: '/teacher',
    target: 'coupon-generate-btn',
    requireTarget: false,
    selectTab: 'coupons',
    selectSection: 'print',
  },
  {
    id: 'teacher-redemptions-tab',
    title: 'Prize Redemptions',
    body: 'Redemption: if students request prizes at the kiosk, you will see them here to approve and hand out.',
    onRoute: '/teacher',
    target: 'staff-tab-redemptions',
    requireTarget: true,
  },
  {
    id: 'teacher-finish',
    title: 'Teacher Add-Ons',
    body: 'That covers the core Teacher tabs! Want a quick look at optional modules like Library and hallway Displays?',
    onRoute: '/teacher',
    target: STAFF_AI_HELP_TOUR_TARGET,
    offerNextTour: 'teacher-features',
  },
];
