# One-time setup for local-folder GCS backups.
# Uses FIREBASE_SERVICE_ACCOUNT_KEY from .env.local when available.
param(
  [string]$Bucket = "",
  [string]$ProjectId = "studio-1273073612-71183",
  [string]$Prefix = "local-folder-backups/studio",
  [int]$RetentionDays = 30,
  [switch]$SkipSchedule,
  [switch]$SkipInitialBackup
)

$ErrorActionPreference = "Stop"

function Resolve-GcloudCmd() {
  $cmd = Get-Command "gcloud" -ErrorAction SilentlyContinue
  if ($cmd) { return $cmd.Source }

  $candidates = @(
    "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd",
    "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd",
    "$env:LOCALAPPDATA\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd"
  )
  foreach ($p in $candidates) { if (Test-Path $p) { return $p } }
  throw "gcloud not found. Install Google Cloud SDK: https://cloud.google.com/sdk/docs/install"
}

function Read-DotEnvValue([string]$FilePath, [string]$Key) {
  if (-not (Test-Path $FilePath)) { return $null }
  foreach ($line in Get-Content $FilePath) {
    if ($line -match "^\s*$([regex]::Escape($Key))\s*=\s*(.+)\s*$") {
      $value = $Matches[1].Trim()
      if (
        ($value.StartsWith('"') -and $value.EndsWith('"')) -or
        ($value.StartsWith("'") -and $value.EndsWith("'"))
      ) {
        $value = $value.Substring(1, $value.Length - 2)
      }
      return $value
    }
  }
  return $null
}

function Ensure-GcloudAuth([string]$Gcloud, [string]$RepoRoot) {
  $authList = (& $Gcloud auth list --format="value(account)" 2>$null | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
  if ($authList) {
    Write-Host "Using existing gcloud account: $($authList | Select-Object -First 1)"
    return
  }

  $envPath = Join-Path $RepoRoot ".env.local"
  $saJson = Read-DotEnvValue $envPath "FIREBASE_SERVICE_ACCOUNT_KEY"
  if ([string]::IsNullOrWhiteSpace($saJson)) {
    throw @"
No active gcloud credentials and FIREBASE_SERVICE_ACCOUNT_KEY was not found in .env.local.
Run:
  gcloud auth login
  gcloud auth application-default login
Then re-run this script.
"@
  }

  $sa = $saJson | ConvertFrom-Json
  if ([string]::IsNullOrWhiteSpace($sa.client_email) -or [string]::IsNullOrWhiteSpace($sa.private_key)) {
    throw "FIREBASE_SERVICE_ACCOUNT_KEY in .env.local is missing client_email or private_key."
  }

  $keyDir = Join-Path $RepoRoot ".local-backups"
  New-Item -ItemType Directory -Force -Path $keyDir | Out-Null
  $keyPath = Join-Path $keyDir "gcs-sa-key.json"
  $writeKeyScript = @'
require('dotenv').config({ path: '.env.local' });
const fs = require('fs');
const raw = process.env.FIREBASE_SERVICE_ACCOUNT_KEY;
if (!raw) throw new Error('FIREBASE_SERVICE_ACCOUNT_KEY missing');
const parsed = JSON.parse(raw);
parsed.private_key = parsed.private_key.replace(/\\n/g, '\n');
const keyPath = process.argv[1];
fs.writeFileSync(keyPath, JSON.stringify(parsed, null, 2));
'@
  Push-Location $RepoRoot
  try {
    node -e $writeKeyScript -- $keyPath | Out-Null
  } finally {
    Pop-Location
  }

  $projectId = [string]$sa.project_id
  Write-Host "Activating service account: $($sa.client_email) (project: $projectId)"
  & $Gcloud auth activate-service-account $sa.client_email --key-file=$keyPath --project=$projectId | Out-Null
}

function Ensure-BackupBucket([string]$Gcloud, [string]$ProjectId, [string]$BucketName) {
  $exists = $false
  try {
    $output = & $Gcloud storage buckets describe "gs://$BucketName" --format="value(name)" 2>$null
    if ($LASTEXITCODE -eq 0 -and -not [string]::IsNullOrWhiteSpace($output)) {
      $exists = $true
    }
  } catch {
    $exists = $false
  }

  if ($exists) {
    Write-Host "Backup bucket already exists: gs://$BucketName"
    return
  }

  Write-Host "Creating backup bucket: gs://$BucketName"
  & $Gcloud storage buckets create "gs://$BucketName" `
    --project=$ProjectId `
    --location=us-central1 `
    --uniform-bucket-level-access `
    --public-access-prevention | Out-Null
}

function Write-BackupConfig([string]$RepoRoot, [string]$BucketName, [string]$Prefix, [int]$RetentionDays) {
  $configPath = Join-Path $RepoRoot ".gcs-backup.env"
  @(
    "# Local GCS backup config (generated by scripts/setup-gcs-backup.ps1)",
    "GCS_BACKUP_BUCKET=$BucketName",
    "GCS_BACKUP_PREFIX=$Prefix",
    "GCS_BACKUP_RETENTION_DAYS=$RetentionDays"
  ) | Set-Content -Path $configPath -Encoding UTF8
  Write-Host "Wrote config: $configPath"
}

function Register-BackupSchedule([string]$RepoRoot) {
  $taskName = "SchoolArcade-Studio-GCS-Backup"
  $launcher = Join-Path $RepoRoot "scripts\run-gcs-backup.cmd"
  $trCommand = "`"$launcher`""

  try {
    $delete = Start-Process -FilePath "schtasks.exe" -ArgumentList "/Delete","/TN",$taskName,"/F" -Wait -PassThru -WindowStyle Hidden
    $createArgs = "/Create","/TN",$taskName,"/SC","DAILY","/ST","03:00","/TR",$trCommand,"/F"
    $create = Start-Process -FilePath "schtasks.exe" -ArgumentList $createArgs -Wait -PassThru -WindowStyle Hidden
    if ($create.ExitCode -ne 0) {
      throw "schtasks /Create exited $($create.ExitCode)"
    }
    Write-Host "Scheduled daily backup task: $taskName (03:00 local time)"
  } catch {
    Write-Warning "Could not register Windows scheduled task automatically: $($_.Exception.Message)"
    Write-Host "Run manually from an elevated Command Prompt:"
    Write-Host "  schtasks /Create /TN `"$taskName`" /SC DAILY /ST 03:00 /TR `"$launcher`" /F"
  }
}

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$Gcloud = Resolve-GcloudCmd

Ensure-GcloudAuth -Gcloud $Gcloud -RepoRoot $RepoRoot

$projectId = (& $Gcloud config get-value project 2>$null).Trim()
if ([string]::IsNullOrWhiteSpace($projectId) -or $projectId -eq "(unset)") {
  $projectId = $ProjectId
  & $Gcloud config set project $projectId | Out-Null
}

if ([string]::IsNullOrWhiteSpace($Bucket)) {
  $Bucket = "$projectId-local-backups"
}

Write-Host "GCP project: $projectId"
Write-Host "Backup bucket: gs://$Bucket/$Prefix/"

Ensure-BackupBucket -Gcloud $Gcloud -ProjectId $projectId -BucketName $Bucket
Write-BackupConfig -RepoRoot $RepoRoot -BucketName $Bucket -Prefix $Prefix -RetentionDays $RetentionDays

if (-not $SkipSchedule) {
  Register-BackupSchedule -RepoRoot $RepoRoot
}

if (-not $SkipInitialBackup) {
  Write-Host "Running initial backup..."
  & (Join-Path $RepoRoot "scripts\backup-local-folder-to-gcs.ps1")
}

Write-Host "GCS backup setup complete."
