export type { StaffPortalRole, StaffPortalTabDef, StaffPortalTabKind, StaffPortalTabView } from './types';
export {
  STAFF_PORTAL_TAB_REGISTRY,
  STAFF_PORTAL_CANONICAL_TAB_ORDER,
  staffPortalAddOnTabs,
  staffPortalAdminAddOnIsOn,
  staffPortalAllAddOnTabValues,
  staffPortalAppendTabsInCanonicalOrder,
  staffPortalMergePinnedAddOnValues,
  staffPortalOrderMainTabs,
  staffPortalOrderPinnedAddOnValues,
  staffPortalSortPinnedTabDefs,
  staffPortalSortTabs,
  staffPortalTeacherPinSideEffects,
  staffPortalCoreTabs,
  staffPortalDefaultTab,
  staffPortalPinWelcomeFirst,
  staffPortalIsTeacherOperatedTab,
  staffPortalTabByValue,
  staffPortalTabDescription,
  staffPortalTabsForRole,
  staffPortalTeacherOperatedAdminNote,
  staffPortalSchoolwideTeacherNote,
  STAFF_PORTAL_SCHOOLWIDE_TEACHER_TAB_VALUES,
  STAFF_PORTAL_WELCOME_PILLAR_TABS,
  STAFF_PORTAL_WELCOME_PILLAR_SET,
  normalizeStaffPortalTabValue,
  normalizeStaffPortalTabValues,
} from './tabRegistry';
export {
  staffPortalTabIsValid,
  useStaffPortalTabs,
  type UseStaffPortalTabsOptions,
  type UseStaffPortalTabsResult,
} from './useStaffPortalTabs';
export {
  staffPortalNavLayoutPatch,
  staffPortalRoleFromLoginState,
  staffPortalUsesSidebar,
  staffPortalUsesSidebarForLogin,
} from './navLayout';
